# Generated by Django 3.1.5 on 2021-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphaval', models.CharField(max_length=150, unique=True, verbose_name='Enter Item')),
                ('integerval', models.IntegerField(default=0, verbose_name='Integer')),
                ('alphanumval', models.CharField(max_length=150, unique=True, verbose_name='Alpha num')),
            ],
        ),
    ]
